version: "3.9"
services:
 dbpost:
  image: postgres:latest
  environment:
   POSTGRES_DB: dbcompose
   POSTGRES_USER: usrcompose
   POSTGRES_PASSWORD: passcompose
  volumes:
   - ./init_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  ports:
   - 5432:5432